pipeline {
    agent any

    environment {
        POM_VERSION = ""
    }

    stages {
        stage('Build') {
            agent {
                docker { 
                    image 'node:6-alpine',
                    args:'-p 3000:3000'
                     }
            }
            stages {
                stage('build'){
                    steps{
                        sh: 'npm install'
                    }
                }
            }
            stages {
                stage('execute application'){
                    steps{
                        sh: 'npm start'
                    }
                }
            }
        }
    }
}
