pipeline {
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('execute application'){
            steps{
                sh 'npm start'
            }
            }
        }
    }

