pipeline {
    agent { 
            docker { 
                image 'node:16.17.1-alpine',
            }
        }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('execute application'){
            steps{
                sh 'npm start'
            }
        }
    }
}

